project_id = "sqgsbekwvuccyompzhpv"

[functions.create-paypal-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.apply-referral]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.analyze-video]
verify_jwt = false
